services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cryptodb
      POSTGRES_USER: cryptouser
      POSTGRES_PASSWORD: cryptopass
    networks:
      - kafka-net

networks:
  kafka-net:
    external: true
    name: kafka_default